# Generated by Django 5.0 on 2024-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
