# Generated by Django 5.0 on 2024-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_categoria_imagen_remove_post_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='blog.categoria'),
        ),
    ]
